name: unittest
on:
  push:
    branches:
      - '*'
    paths-ignore:
      - '.github/**'
      - '*.md'
      - 'assets/**'
      - 'LICENSE'
      - 'node_modules/*'
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: "0 */2 * * *"
jobs:
  unittests:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - uses: zcong1993/setup-timezone@master
        with:
          timezone: America/Chicago
      - run: yarn install --frozen-lockfile
      - run: yarn run test
        env:
          MONGODB: mongodb://localhost:27017/ncovapi
